### ISSUE TITLE
were you successful?

### ISSUE THREAD

**Issue by mankins** [clinton0313/nie-getter#2]
did you actually get an appointment? Or is this script why there are no appointments?

**Comment by clinton0313** [comment]
Yes, this worked for me. I made a mistake at first of inputting my passport expiry date in the expiry date field, but that field needs to be left blank for extending a student visa. As soon as I left that field blank I got it my first morning running it. Try around 830am to as late as 1030 am BCN time.

**Comment by clinton0313** [comment]
If you use it, let me know how it goes for you.

**Comment by mankins** [comment]
Thanks, I'll give it a go. BTW: Thanks for updating the README.

**Comment by clinton0313** [comment]
Yeah, honestly this is the first thing I've ever written in Python and/or uploaded to Github. I just shared it to my program's whatsapp at school and didn't really expect anyone to be using it. I could do more to make it scalable to all the other applications and also more user-friendly, etc.

**Comment by mankins** [comment]
@clinton0313 it's great, thanks for sharing! You can always change code, but this is useful as is, so that's great.
